### PR TITLE
Update French translation back to 100%

### PR DESCRIPTION
**Pull request by trebmuh**
I've translated this through the github interface, hence I didn't try to compile, then I **_hope_** I didn't make any code mistake and it'll compile fine. Please, test before merging (I will not have a dev computer with me until sometime in the 1st week of March).

Hope that helps.

### CODE REVIEW

**Comment by louis-barman** [comment]
Great thanks I am away my self at the momentum and I will have a look at it in a few days. 

(There is actually no new text I have just split it differently. To hopefully make it easier to translate in future and I have removed the URL from the translated code. I might look at a few others as it is just a case of coping and pasting the translations we had before into the right place.) 

Thanks again.

**Comment by pianobooster** [comment]
I was just about to merge and then I noticed this English label with the English tool tip.

IMG_20200214_123241749

I don't understand why this is not translated . Did you miss these strings or (I suspect) that there is something else strange going on. I am still investigating.

**Comment by trebmuh** [comment]
Those strings aren't in the [French translation file](https://github.com/captnfab/PianoBooster/blob/master/translations/pianobooster_fr.ts), hence I can't translate them.

**Comment by trebmuh** [comment]
You can see that I've translated these, they are the [2 first one in this very PR](https://github.com/captnfab/PianoBooster/pull/217/files).

**Comment by pianobooster** [comment]
My apologises my message above was my mistake entirely. I have checked your translations by running PB but as I thought should have just merged this PR immediately.

**Comment by trebmuh** [comment]
No worries at all.
Thanks for taking some time to check it, and thanks for the merge.

**Pull request merged**
