### PR TITLE
compile from pianobooster.pro

### PR DESCRIPTION
**Pull request by admsasha**
successful compilation via pianobooster.pro file

### CODE REVIEW

**Comment by captnfab** [comment]
Hi,
Thanks for your PR.

I have a problem with "f967a7e delete render text over ftgl", since it breaks translation of notes name.
Could you do a new pull request without this particular commit?
If you really want to get rid of ftgl, let's talk about that in a separate PR.

**Comment by glixx** [comment]
It's better do not translate notes name, but to be workable everywhere and in Windows too.

**Comment by captnfab** [comment]
I won't merge f967a7e until we have an other mean to translate notes.

**Comment by glixx** [comment]
I guess we should go by 3 ways:
- use own font (by default)
- use system font
- do not use font
And to have compillation options for 3 ways. So users will have options how to build.

**Comment by captnfab** [comment]
@glixx: sure, no problem for letting the user choose.

**Pull request closed without merging**
