### PR TITLE
Update pkgbuild

### PR DESCRIPTION
**Pull request by sparunakian**
Hi,

This MR modifies ArchLinux packaging.

Modifications of the PKGBUILD:
- bumps the target version to 0.7.2b
- adds rtmidi as dependency and build dependency (won't build and run without it)
- uses sources from Github release

I've made this MR for the develop branch, but I think these modifications could go directly to master. Feel free to cherry pick modifications.

Regards,

Stéphane

### CODE REVIEW

**Comment by louis-barman** [comment]
Yes thanks for this. I will also cherry pick this change an put it into master as you suggested.

Would you be interested in becoming a beta tester for ArchLinux? If so please see this thread http://piano-booster.2625608.n2.nabble.com/Helping-with-Piano-Booster-eg-testing-translators-tp7572826.html

There are still lots of  `0.7.1` in the code that i'll fix as well. 

```
grep -nHIirF -- 0.7.1 (in directory: PianoBooster)
./Changelog.txt:20:v0.7.1
./pkgs/slack/pianobooster.info:2:VERSION="0.7.1"
./pkgs/slack/pianobooster.info:4:DOWNLOAD="PianoBooster-0.7.1.tar.gz"
./pkgs/slack/pianobooster.SlackBuild:13:VERSION=${VERSION:-0.7.1}
./pkgs/rpm/pianobooster.spec:10:Version:        0.7.1
./pkgs/deb/pianobooster.dsc:5:Version: 0.7.1
./pkgs/deb/pianobooster.dsc:25: 7e32ca7fc4eb65ac39a5bc5d95cd5709 8511345 PianoBooster-0.7.1.tar.gz
./pkgs/arch/PKGBUILD:9:pkgver=0.7.1
```

**Comment by sparunakian** [comment]
Thank you for PianoBooster.
I'll check the thread.

**Comment by louis-barman** [comment]
Hello @sparunakian Are you involved with ArchLinux at all? are these files any use to you or to the  ArchLinux project?  I am thinking it might be better just to delete these packages as I don't really want to maintain them, but I am happy leave them if you need them. Please let me know what you think.

Also I contacted the debian maintainer and she wrote:

> I don't think that "PianoBooster/pkgs/deb/" is really useful, to be
honest. I feel that, afaik, you can probably get rid of it without any
problem.

**Comment by sparunakian** [comment]
Hi! I'm not involved with the ArchLinux project. PianoBooster is on the Arch User Repository (AUR), where anyone can put packages. The current maintainer has not updated the package which is stuck at 0.6.4b. As far I know, there is no PKGBUILD apart from the one in this repository which allows to package PianoBooster 0.7.2b for ArchLinux and derivatives. I think this should stay here until the package on AUR is updated, hoping it doesn't take too long.

**Pull request merged**
