### PR TITLE
Restored the German integrated help page translation.

### PR DESCRIPTION
**Pull request by louis-barman**

### CODE REVIEW

**Comment by louis-barman** [comment]
This was quite a lot of work to restore the German help page. I chose German as it was one of the most complete translations. I will probably leave the help page on the other languages untranslated unless we get more volunteers to help.

**Comment by trebmuh** [comment]
Sounds good.

If I'm not wrong (please, correct me if so), the French one is translated as well.

**Comment by louis-barman** [comment]
Yes the French one is the only one that has 100% translation as it was merged earlier. Thank you @trebmuh

**Comment by trebmuh** [comment]
OK, no worries.

**Pull request merged**
