### PR TITLE
Initial piano key forecasting

### PR DESCRIPTION
**Pull request by marcodiegomesquita**
I want to implement "piano key forecasting" in PianoBooster. This is still WIP and I'll need some help to get it to work the way it should, but right now it is already working for some simple exercises.

My fork shows the piano keys filling up as music progresses and when they finally filled, that means it is time to hit the key.

The follwoing image illustrates what I'm trying to do.

forecast

### CODE REVIEW

**Comment by trebmuh** [comment]
That is a nice idea. Very pedagogical.
I'd be inclined to make it a selectable option.

**Comment by louis-barman** [comment]
Hi @marcodiegomesquita ,

I am the original author of Piano Booster which I started back in 2008. At that time Guitar Hero was very popular played on a fake guitar and then someone wrote a version for a real MIDI piano keyboard called Synthesia. 

One of the motivations for me writing Piano Booster was to help people to learn to read standard musical notation and so I had the notes moving horizontally on a stave rather than vertically like in Synthesia. I really recommend that you (and everyone) tries to learn to read standard musical notation from a printed piano score so that you can 'forecast' what are the next notes to play from the score. If you are not interested in learning to read sheet music then I recommend that you try  Synthesia see https://synthesiagame.com/ . Even synthesia users asked the author of Synthesia to add standard musical notation to Synthesia which eventually the author did.  I have heard that some user find it very beneficial to learn to play the piano using both Synthesia and PianoBooster programs. 

However what I don't want to do is to turn PianoBooster into Synthesia as I want to stick to the core principle of Piano Booster is to help users to play the piano and to read sheet music. So I really hope you won't be offended if I decline this pull request. Also I would be declining this pull request as it was made to the master branch and not to the develop branch. All pull request should be made to the develop branch please.  

Of course I encourage you to keep going with this in your own repo if this is something that you really want. I am happy for you to open a topic about this in the users forum if you like you can add a links to your code changes. But also I encourage you and everyone try and learn to read music to forecast the next notes to play.

I haven't yet tested your code out yet  and I intend  to try it out over the next few days to see if there are any bug fixes you have made to the piano display as currently I don't think it works properly.

**Comment by trebmuh** [comment]
> All pull request should be made to the develop branch please.

You should add this to [the README](https://github.com/captnfab/PianoBooster#contributing).

**Comment by trebmuh** [comment]
@louis-barman @pianobooster 

> All pull request should be made to the develop branch please.

You should add this to [the README](https://github.com/captnfab/PianoBooster#contributing).

**Comment by marcodiegomesquita** [comment]
> Hi @marcodiegomesquita ,
> 

Hi!

Right now the implementation is very buggy and hackish. To implement it correctly I need to find a way to reliably determine, inside the method getKeyboardInfo, how long one has to wait for a note to be played. Can you help me with that?

Also in the future it would be good to keep the keyboard key lighted for the duration of the note. Can you help me with that too?

> One of the motivations for me writing Piano Booster was to help people to learn to read standard musical notation and so I had the notes moving horizontally on a stave rather than vertically like in Synthesia. I really recommend that you (and everyone) tries to learn to read standard musical notation from a printed piano score so that you can 'forecast' what are the next notes to play from the score. If you are not interested in learning to read sheet music then I recommend that you try Synthesia see https://synthesiagame.com/ . Even synthesia users asked the author of Synthesia to add standard musical notation to Synthesia which eventually the author did. I have heard that some user find it very beneficial to learn to play the piano using both Synthesia and PianoBooster programs.
> 
> However what I don't want to do is to turn PianoBooster into Synthesia as I want to stick to the core principle of Piano Booster is to help users to play the piano and to read sheet music. So I really hope you won't be offended if I decline this pull request. Also I would be declining this pull request as it was made to the master branch and not to the develop branch. All pull request should be made to the develop branch please.
> 
Now about the feature itself. There are some very important points that I think must be taken into account:

1. Not on by default:

	Just like the "Show piano keyboard" this should be optional and off by default.

2. Simple and non-obtrusive:

	The feature can be small in terms of code and visual load.

3. Good complementary display:

	This may be very helpful to quickly determine what are the next keys to be played and for how long one should wait to press the key. It may also help with hand and figer positioning since you know what are the next notes to be played and in what order.

4. Does not steer the student away from learning standard notation:

	The standard notation will continue on the UI exactly the same way it is now. Just having a small help forecasting the next notes to be played will not make anybody stop considering the standard notation on the screen.
	Consider that guitar tabs do no harm to classical guitar players and are frequently used as a first step when learning to play the classical guitar.

5. Very helpful for beginners:

	After some familiarity, it is expected that the user will use mostly the standard notation view. The forecast is not really much more convenient than the standard notation except for beginners.

6. It is innovative:

	I don't remember ever seen this specific help on any other software. This matches well with pianobooster history of being a different learning tool that can help in ways that most other tools can't.

7. May have a very positive impact on pianobooster popularity

	It can make learning and playing (specially for beginners) much easier and fun. This may significantly impact pianobooster popularity and bring more users and developers.

So, I kindly ask you to please reconsider you stance on not accepting it.

**Comment by pianobooster** [comment]
Ok can you please email me directly on louisjbarman@gmail.com and maybe we can have a call together about this. But I really need to first try this out myself to see how it works before I can judge it. 

One possible idea i am thinking of is to implement this as a plugin. Please see https://doc.qt.io/qt-5/plugins-howto.html#the-low-level-api-extending-qt-applications page and The Plug & Paint example. 

Also I am trying to relaunch the PB website and make you tube videos.  I am trying to first get a new release out for version 0.7.3 first.. so any major change would need to wait until after that release has been completed. But we can talk more about this if we have a call.

**Comment by pianobooster** [comment]
Hi  @marcodiegomesquita 

Thanks for being on the call with me. As discussed I am closing this as it is a PR on the master branch. If this was to be accepted into this PB repository  it would need to be worked on in its own separate branch while it was being completed.  

However as explained on the call the whole reason for me to write PB in the first place is to teach musical novices to play the piano AND to read a musical score. For this the students need to learn to look at the musical score find the next notes to play.  I think having two different places to look at to find the next note to play just makes things more complicated.

**Pull request closed without merging**
