### PR TITLE
minor patches from debian package

### PR DESCRIPTION
**Pull request by barak**
These are minor patches from packaging for debian.
- some grammar
- add cmake option for installing executables somewhere other than PREFIX/bin, e.g., /usr/games/
- tell desktop files to pass mime parameters to the trampoline executable scripts

### CODE REVIEW

**Comment by glixx** [comment]
@barak , 
1) there is build option NO_LICENSE=ON to skip license.txt installation.
2) svg icon looks wrong installed:
Screenshot_20190903_121237
3) do not need to install logo svg icon.

**Comment by barak** [comment]
I took the .svg logo installation from the debian branch, with commits by glixx, 6255b5a40d6db26d1a8240c59aaac8a6ad8b4f3b, will remove (although a proper scalable icon would be nice.)

**Comment by glixx** [comment]
We removed deprecated debian branch.

**Comment by barak** [comment]
I uploaded the new release to Debian, using the new NO_LICENSE option.

**Pull request merged**
